# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'INSTALL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase SDK
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'

  # Google Sign In (for Google Auth)
  pod 'GoogleSignIn'

  target 'INSTALLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'INSTALLUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
